import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from 'sonner'
import Providers from "./providers";
import dynamic from 'next/dynamic';
import { DemoProvider } from "../contexts/demoContext";

// Dynamic import AppBar to prevent SSR issues during error page rendering
const AppBarClient = dynamic(() => import("../components/appBClient"), {
  ssr: false,
  loading: () => (
    <div className="h-16 bg-gradient-to-r from-primary to-secondary animate-pulse" />
  )
});




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "N4W6NRQ0UlAyRp9qUzIIACzm4eijyuD32DfXlLVHXpM",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <Providers>
        <DemoProvider>
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <div>
              <AppBarClient/>
            </div>
            {children}
            <Toaster
            richColors
              position="bottom-left"
            />
          </body>
        </DemoProvider>
      </Providers>
    </html>
  );
}
